name: Test
run-name: ${{ github.actor }} is running the unit tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install package
        run: pip install ".[dev]"

      - name: Run tests
        run: |
          tox -e py311-pytest
